"""anadir push_token a users

Revision ID: 8afb2f1757a7
Revises: 32dd032060ba
Create Date: 2026-09-03 11:17:49.011165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8afb2f1757a7'
down_revision: Union[str, None] = '32dd032060ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('push_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'push_token')
    # ### end Alembic commands ###
